/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-10-08 17:45:39 UTC)
 * on 2020-07-22 at 10:19:03 UTC
 * Modify at your own risk.
 */

package biz.turnonline.ecosystem.search.model;

/**
 * Model definition for Invoice.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the TurnOnline.biz Search Engine. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings( "javadoc" )
public final class Invoice
        extends com.google.api.client.json.GenericJson
{

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.String companyId;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.String id;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.String invoiceNumber;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.String owner;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.String paymentIdentification;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.util.List<java.lang.String> productCodes;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.String year;

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getCompanyId()
    {
        return companyId;
    }

    /**
     * @param companyId companyId or {@code null} for none
     */
    public Invoice setCompanyId( java.lang.String companyId )
    {
        this.companyId = companyId;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getId()
    {
        return id;
    }

    /**
     * @param id id or {@code null} for none
     */
    public Invoice setId( java.lang.String id )
    {
        this.id = id;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getInvoiceNumber()
    {
        return invoiceNumber;
    }

    /**
     * @param invoiceNumber invoiceNumber or {@code null} for none
     */
    public Invoice setInvoiceNumber( java.lang.String invoiceNumber )
    {
        this.invoiceNumber = invoiceNumber;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getOwner()
    {
        return owner;
    }

    /**
     * @param owner owner or {@code null} for none
     */
    public Invoice setOwner( java.lang.String owner )
    {
        this.owner = owner;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getPaymentIdentification()
    {
        return paymentIdentification;
    }

    /**
     * @param paymentIdentification paymentIdentification or {@code null} for none
     */
    public Invoice setPaymentIdentification( java.lang.String paymentIdentification )
    {
        this.paymentIdentification = paymentIdentification;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.util.List<java.lang.String> getProductCodes()
    {
        return productCodes;
    }

    /**
     * @param productCodes productCodes or {@code null} for none
     */
    public Invoice setProductCodes( java.util.List<java.lang.String> productCodes )
    {
        this.productCodes = productCodes;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getYear()
    {
        return year;
    }

    /**
     * @param year year or {@code null} for none
     */
    public Invoice setYear( java.lang.String year )
    {
        this.year = year;
        return this;
    }

    @Override
    public Invoice set( String fieldName, Object value )
    {
        return ( Invoice ) super.set( fieldName, value );
    }

    @Override
    public Invoice clone()
    {
        return ( Invoice ) super.clone();
    }

}
